apps/market/views.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app, send_from_directory, jsonify
from flask_login import current_user, login_required
from apps.detector.models import UserImage, Color, CategoryName, Condition, Size, Favorite
from apps.app import db
from flask_paginate import Pagination, get_page_args
from flask_login import current_user, login_required
from datetime import datetime

market = Blueprint("market", __name__, template_folder="templates")

# ページネーション関数
def image_paginate(lengs):
    if lengs == None:
        lengs = UserImage.query.order_by(UserImage.id.desc()).all()
    page = request.args.get(get_page_args(), type=int, default=1)
    products = lengs[(page-1)*9:page*9]
    pagination = Pagination(page=page, per_page=9, rows=products, total=len(lengs),  css_framework="bootstrap5", search=False)
    
    return pagination

@market.route("/shop/", methods=["GET"])
def shop():
    products = UserImage.query.order_by(UserImage.id.desc()).all()
    return render_template("market/shop-sidebar.html", products=products)

@market.route("/shop/price/<int:price>", methods=["GET"])
def shopprice(price):    
    if price == 1:
        products = UserImage.query.filter(UserImage.price <= 2000 , UserImage.price >= 1000).order_by(UserImage.id.desc()).all()

    if price == 2:
        products = UserImage.query.filter(UserImage.price <= 3000 , UserImage.price >= 2000).order_by(UserImage.id.desc()).all()

    if price == 3:
        products = UserImage.query.filter(UserImage.price <= 4000 , UserImage.price >= 3000).order_by(UserImage.id.desc()).all()
    
    if price == 4:
        products = UserImage.query.filter(UserImage.price <= 5000 , UserImage.price >= 4000).order_by(UserImage.id.desc()).all()

    # pagination = image_paginate(products)

    return render_template("market/shop-sidebar.html", price=price)

# 性別
@market.route("shop/category/<int:key>")
def shopcategory(key):
    products = UserImage.query.filter(UserImage.sexual==key).order_by(UserImage.id.desc()).all()
    
    # pagination = image_paginate()
    
    return render_template("market/shop-sidebar.html", products=products)

# サイズ
@market.route("shop/size/<int:key>")
def shopsize(key):
    
    products = UserImage.query.filter(UserImage.size==key).order_by(UserImage.id.desc()).all()
    
    # pagination = image_paginate(products)
    return render_template("market/shop-sidebar.html", products=products)

@market.route("detail/<int:id>")
def detail(id):
    product = UserImage.query.filter_by(id=id).first()
    color = Color.query.filter_by(id=product.color).first()
    categories = CategoryName.query.filter_by(id=product.category).first()
    condition = Condition.query.filter_by(id=product.condition).first()
    size = Size.query.filter_by(id=product.size).first()
    allproducts = UserImage.query.order_by(UserImage.id.desc()).all()
    
    return render_template("market/single-product.html", product=product, color=color, categories=categories, condition=condition, size=size, allproducts=allproducts)
    
@market.route("/payment/<int:id>", methods=["GET", "POST"])
@login_required
def payment(id):
    product = UserImage.query.filter_by(id=id).first()
    
    return render_template("market/accountant.html", product=product)

@market.route("/paymentComplete/<int:id>", methods=["GET", "POST"])
@login_required
def paymentComplete(id):
    product = UserImage.query.filter_by(id=id).first()
    if product.sold == False:
        product.sold = True
        db.session.commit()
    return render_template("market/purchase.html", product=product)

@market.route("/rental/<int:id>", methods=["GET", "POST"])
def rental(id):
    product = UserImage.query.filter_by(id=id).first()

    return render_template("market/rental.html", product=product)

@market.route("/rentalComplete/<int:id>", methods=["GET", "POST"])
def rentalComplete(id):
    product = UserImage.query.filter_by(id=id).first()
    if product.rental == False:
        product.rental = True
        db.session.commit()
    return render_template("market/rentalok.html", product=product)

@market.route("/favorite/<int:id>", methods=["GET", "POST"])
@login_required
def favorite(id):
    product = UserImage.query.filter_by(id=id).first()
    
    favorite = Favorite(user_id=current_user.id, product_id=product.id)
    db.session.add(favorite)
    db.session.commit()
    
    return redirect(url_for("market.shop"))

@market.route("/wishList", methods=["GET", "POST"])
@login_required
def wishList():
    # お気に入りを取得
    user_id = current_user.id
    favorites = Favorite.query.filter_by(user_id=user_id).all()
    products = []
    for favorite in favorites:
        product = UserImage.query.filter_by(id=favorite.product_id).first()
        if product not in products:
            products.append(product)
        else:
            pass
    return render_template("market/wishlist.html", products=products)

@market.route("/wishList/delete/<int:id>", methods=["GET", "POST"])
def deleteWishList(id):
    favorite = Favorite.query.filter_by(user_id = current_user.id, product_id=id).first()
    db.session.delete(favorite)
    db.session.commit()
    return redirect(url_for("market.wishList"))


@market.route("/search/<string:search>", methods=["GET"])
def search(search):
    search = request.args.get(search)
    
    products = UserImage.query.filter(UserImage.image_name.like("%" + str(search) + "%")).order_by(UserImage.id.desc()).all()
    # categories = UserImage.query.filter(UserImage.category.like("%" + search + "%")).order_by(UserImage.id.desc()).all()
    
    return render_template("market/history.html", products=products)

apps/market/templates/market/accountant.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>お会計ページ</title>

    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/purchase.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/style.css')}}"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500&family=Prata&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <header></header>

    <nav></nav>

    <h1>お会計</h1>
    <div class="flex">
      <img
        src="{{url_for('detector.image_file',filename=product.image_path)}}"
      />

      <div class="right">
        <p class="title"><b>ご注文内容</b></p>
        <p class="text">
          商品名：{{product.image_name}}<br />
          <span class="space"> </span
          >&nbsp;&nbsp;&nbsp;&nbsp;価格：{{product.price}}円<br />
          <!-- 送料<span class="space2">  </span>100円</p> -->
          <!-- <p>合計<span class="space3"> </span>3000円 -->
        </p>
        <br />
        <font size="5px"
          ><b
            >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;合計：{{product.price}}円</b
          ></font
        >

        <form class="radio">
          <input type="radio" name="payment" value="option1" />PayPay
          <input type="radio" name="payment" value="option2" />ApplePay
          <input type="radio" name="payment" value="option3" />ID
          <input type="radio" name="payment" value="option4" />WAON
        </form>

        <audio
          id="audio1"
          src="{{url_for('static', filename='audios/PayPay.mp3')}}"
        ></audio>
        <audio
          id="audio2"
          src="{{url_for('static', filename='audios/Apple_Pay.mp3')}}"
        ></audio>
        <audio
          id="audio3"
          src="{{url_for('static', filename='audios/iD.mp3')}}"
        ></audio>
        <audio
          id="audio4"
          src="{{url_for('static', filename='audios/WAON.mp3')}}"
        ></audio>

        <div class="payment-button-container">
          <a href="{{url_for('market.paymentComplete', id=product.id)}}">
            <button id="playButton" onclick="redirectToSelected()">
              支払い
            </button></a
          >
          <button onclick="redirectToPage()">キャンセル</button>
        </div>
      </div>
    </div>

    <audio id="audio" src=""></audio>
    <script src="{{url_for('static', filename='js/purchase.js')}}"></script>
  </body>
</html>

apps/market/templates/market/favorite.html
{%extends "detector/index.html"%} {%block title%}お気に入りリスト{%endblock%}
{%block content%}
<body class="homepage">
  <main>
    <section>
      <div class="container">
        <div class="d-flex justify-content-between align-items-center mt-5">
          <h4>お気に入りリスト</h4>
          <nav class="breadcrumb fs-6">
            <a class="breadcrumb-item nav-link" href="#">Home</a>
            <a class="breadcrumb-item nav-link" href="#">Pages</a>
            <span class="breadcrumb-item active" aria-current="page"
              >Wishlist</span
            >
          </nav>
        </div>
      </div>
    </section>

    <section id="Wishlist" class="py-5 mb-5">
      <div class="container">
        <div class="row text-dark my-3">
          <div class="col-5 text-uppercase">商品</div>
          <div class="col-2 text-uppercase">価格</div>
          <div class="col-2 text-uppercase">在庫</div>
        </div>
        {% for product in products %}
        <div class="product-wrapper">
          <div class="product-item row align-items-center mb-4">
            <div class="col-4 col-md-1 d-flex align-items-center text-left">
              <a href="{{url_for('market.detail', id=product.id)}}">
                <img
                  srcset="
                    {{url_for('detector.image_file',filename=product.image_path)}}
                  "
                  alt="wishlist"
                  class="img-fluid" />
              </a>
            </div>
            <div class="col-8 col-md-4">
              <h3 class="item-title text-uppercase fs-5">
                <a href="{{url_for('market.detail', id=product.id)}}"
                  >{{product.image_name}}</a
                >
              </h3>
            </div>
            <div class="col-3 col-md-2 product-price text-left">
              <span class="item-price">{{product.price}}円</span>
            </div>
            {% if product.sold == True %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: red">購入不可</span>
            </div>
            {% else %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: blue">購入可</span>
            </div>
            <div class="col-3 col-md-2 wishlist-add text-left">
              <a
                class="btn btn-outline-dark text-uppercase"
                title="Add to Cart"
                href="{{url_for('market.detail', id=product.id)}}"
                >購入する</a
              >
            </div>
            {% endif %} {% if product.rental == True %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: red">レンタル不可</span>
            </div>
            {% else %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: blue">レンタル可</span>
            </div>
            <div class="col-3 col-md-2 wishlist-add text-left">
              <a
                class="btn btn-outline-dark text-uppercase"
                title="Add to Cart"
                href="{{url_for('market.rental', id=product.id)}}"
                >レンタルする</a
              >
            </div>
            {% endif %}

            <div class="col-3 col-md-1 text-left">
              <div class="cart-remove">
                <a href="#">
                  <svg width="32px">
                    <use xlink:href="#trash"></use>
                  </svg>
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </section>
  </main>
  {%endblock%}
</body>

apps/market/templates/market/history.html
{%extends "detector/index.html"%} {%block title%}取引履歴リスト{%endblock%}
{%block content%}
<body class="homepage">
  <main>
    <section>
      <div class="container">
        <div class="d-flex justify-content-between align-items-center mt-5">
          <h4>取引履歴リスト</h4>
          <nav class="breadcrumb fs-6">
            <a class="breadcrumb-item nav-link" href="#">Home</a>
            <a class="breadcrumb-item nav-link" href="#">Pages</a>
            <span class="breadcrumb-item active" aria-current="page"
              >History</span
            >
          </nav>
        </div>
      </div>
    </section>

    <section id="Wishlist" class="py-5 mb-5">
      <div class="container">
        <div class="row text-dark my-3">
          <div class="col-5 text-uppercase">商品</div>
          <div class="col-2 text-uppercase">価格</div>
          <div class="col-2 text-uppercase">在庫</div>
        </div>

        {% for product in products %}
        <div class="product-wrapper">
          <div class="product-item row align-items-center mb-4">
            <div class="col-4 col-md-1 d-flex align-items-center text-left">
              <a href="{{url_for('market.detail', id=product.id)}}">
                <img
                  srcset="
                    {{url_for('detector.image_file',filename=product.image_path)}}
                  "
                  alt="history"
                  class="img-fluid" />
              </a>
            </div>
            <div class="col-8 col-md-4">
              <h3 class="item-title text-uppercase fs-5">
                <a href="{{url_for('market.detail', id=product.id)}}"
                  >{{product.image_name}}</a
                >
              </h3>
            </div>
            <div class="col-3 col-md-2 product-price text-left">
              <span class="item-price">{{product.price}}円</span>
            </div>
            {% if product.sold == True %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: red">購入不可</span>
            </div>
            {% else %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: blue">購入可</span>
            </div>
            <div class="col-3 col-md-2 wishlist-add text-left">
              <a
                class="btn btn-outline-dark text-uppercase"
                title="Add to Cart"
                href="{{url_for('market.detail', id=product.id)}}"
                >購入する</a
              >
            </div>
            {% endif %} {% if product.rental == True %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: red">レンタル不可</span>
            </div>
            {% else %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: blue">レンタル可</span>
            </div>
            <div class="col-3 col-md-2 wishlist-add text-left">
              <a
                class="btn btn-outline-dark text-uppercase"
                title="Add to Cart"
                href="{{url_for('market.rental', id=product.id)}}"
                >レンタルする</a
              >
            </div>
            {% endif %}

            <div class="col-3 col-md-1 text-left">
              <div class="cart-remove">
                <a href="#">
                  <svg width="32px">
                    <use xlink:href="#trash"></use>
                  </svg>
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </section>
  </main>
  {%endblock%}
</body>

apps/market/templates/market/rental.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>お会計ページ</title>

    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/rental.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/style.css')}}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500&family=Prata&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <header></header>

    <nav></nav>

    <h1>お会計</h1>
    <div class="flex">
      <img
        src="{{url_for('detector.image_file',filename=product.image_path)}}"
      />

      <div class="right">
        <p class="title"><b>ご注文内容</b></p>
        <p class="text">
          商品名：{{product.image_name}}
          <span class="space"> </span>レンタル価格：{{product.price}}円<br />
          <!-- 送料<span class="space2">  </span>100円</p> -->
          <!-- <p>合計<span class="space3"> </span>3000円 -->
        </p>
        <font color="red"><p>※レンタル期間は通常7日間です。</p></font>
        <br />
        <font size="5px"
          ><b
            >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;合計：{{product.price}}円</b
          ></font
        >

        <form class="radio">
          <input type="radio" name="payment" value="option1" />PayPay
          <input type="radio" name="payment" value="option2" />ApplePay
          <input type="radio" name="payment" value="option3" />ID
          <input type="radio" name="payment" value="option4" />WAON
        </form>

        <audio
          id="audio1"
          src="{{url_for('static', filename='audios/PayPay.mp3')}}"
        ></audio>
        <audio
          id="audio2"
          src="{{url_for('static', filename='audios/Apple_Pay.mp3')}}"
        ></audio>
        <audio
          id="audio3"
          src="{{url_for('static', filename='audios/iD.mp3')}}"
        ></audio>
        <audio
          id="audio4"
          src="{{url_for('static', filename='audios/WAON.mp3')}}"
        ></audio>

        <div class="payment-button-container">
          <a href="{{url_for('market.rentalComplete', id=product.id)}}">
            <button id="playButton" onclick="redirectToSelected()">
              支払い
            </button></a
          >
          <button onclick="redirectToPage()">キャンセル</button>
        </div>
      </div>
    </div>

    <audio id="audio" src=""></audio>
    <script src="{{url_for('static', filename='js/rental.js')}}"></script>
  </body>
</html>

apps/market/templates/market/shop-sidebar.html
{%extends "detector/index.html"%} {%block title%}HOME{%endblock%}zw {%block
content%}
<body class="homepage">
  <div class="preloader text-white fs-6 text-uppercase overflow-hidden"></div>

  <!-- トップ画面の画像 -->
  <section class="hero-section jarallax">
    <div class="img-wrap2">
      <img
        src="{{url_for('static', filename='images/closet4.png')}}"
        class="jarallax-img" />
    </div>
    <div class="py-5">
      <div class="container">
        <div class="row mt-5">
          <div
            class="d-flex flex-wrap flex-column justify-content-center align-items-center my-5 py-5 text-white">
            <h1 class="page-title text-uppercase mt-5 display-4">Shop</h1>
            <nav class="breadcrumb text-white">
              <a class="breadcrumb-item" href="{{url_for('detector.index')}}"
                >Home</a
              >
              <a class="breadcrumb-item" href="#">Pages</a>
              <span class="breadcrumb-item active" aria-current="page"
                >Shop</span
              >
            </nav>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- 商品カテゴリページ -->
  <div class="py-5">
    <div class="container">
      <div class="row flex-md-row-reverse g-5">
        <main class="main-content col-md-9">
          <div class="row py-2">
            <div class="col-md-9">
              <span>商品一覧</span>
            </div>
            <div class="col-md-3">
              <select
                class="form-select border-0"
                aria-label="Default select example">
                <option selected>All</option>
                <option value="1">MEN</option>
                <option value="2">WOMEN</option>
                <option value="3">UNISEX</option>
                <option value="4">その他</option>
              </select>
            </div>
          </div>
          <div class="row my-5">
            {% for product in products %}
            <div class="col-md-4 mb-5 product-item">
              <div class="image-holder position-relative">
                <a href="{{url_for('market.detail', id=product.id)}}">
                  <img
                    src="{{url_for('detector.image_file',filename=product.image_path)}}"
                    alt="categories"
                    class="product-image img-fluid" />
                </a>
                <!-- お気に入り機能 -->
                <a
                  href="{{url_for('market.favorite', id=product.id)}}"
                  class="btn-icon btn-wishlist">
                  <svg
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    class="svg-color">
                    <use xlink:href="#heart"></use>
                  </svg>
                </a>

                <div class="product-content">
                  <h5 class="element-title text-uppercase fs-6 mt-3">
                    <a href="{{url_for('market.detail', id=product.id)}}"
                      >{{product.image_name}}</a
                    >
                  </h5>
                  <a
                    href="#"
                    class="text-decoration-none"
                    data-after="Add to cart"
                    ><span>{{product.price}}円</span></a
                  >
                  {% if product.sold == True %}
                  <h6 class="text-uppercase fs-6 mt-3" style="color: red">
                    SOLD
                  </h6>
                  {% elif product.rental == True %}
                  <h6 class="text-uppercase fs-6 mt-3" style="color: red">
                    RENTALED
                  </h6>
                  {% endif %}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </main>

        <aside class="col-md-3">
          <div class="sidebar">
            <div class="sidebar-categories border-animation-left mb-5">
              <div class="text-dark text-uppercase mb-4">
                <b>商品カテゴリ:</b>
              </div>
              <ul class="list-unstyled">
                <li>
                  <a href="{{url_for('market.shop')}}" class="item-anchor"
                    >All</a
                  >
                </li>
                <li>
                  <a
                    href="{{url_for('market.shopcategory', key=1)}}"
                    class="item-anchor"
                    >MEN</a
                  >
                </li>
                <li>
                  <a
                    href="{{url_for('market.shopcategory', key=2)}}"
                    class="item-anchor"
                    >WOMEN</a
                  >
                </li>
                <li>
                  <a
                    href="{{url_for('market.shopcategory', key=3)}}"
                    class="item-anchor"
                    >UNISEX</a
                  >
                </li>
                <li>
                  <a
                    href="{{url_for('market.shopcategory', key=4)}}"
                    class="item-anchor"
                    >その他</a
                  >
                </li>
              </ul>
            </div>
            <div class="product-filter padding-small">
              <div class="text-dark text-uppercase"><b>検索条件:</b></div>
              <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                  <div class="accordion-header" id="heading-one">
                    <button
                      class="accordion-button py-3"
                      type="button"
                      data-bs-toggle="collapse"
                      data-bs-target="#collapse-one"
                      aria-expanded="true"
                      aria-controls="collapse-one">
                      <span class="accordion-title fs-3">Price</span>
                    </button>
                  </div>
                  <div
                    id="collapse-one"
                    class="accordion-collapse collapse show"
                    aria-labelledby="heading-one">
                    <div class="accordion-body">
                      <a href="{{url_for('market.shopprice', price=1)}}"
                        >1,000円 - 2,000円</a
                      >
                      <a href="{{url_for('market.shopprice', price=2)}}"
                        >2,000円 - 3,000円</a
                      >
                      <a href="{{url_for('market.shopprice', price=3)}}"
                        >3,000円 - 4,000円</a
                      >
                      <a href="{{url_for('market.shopprice', price=4)}}"
                        >4,000円 - 5,000円</a
                      >
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <div class="accordion-header" id="heading-two">
                    <button
                      class="accordion-button py-3"
                      type="button"
                      data-bs-toggle="collapse"
                      data-bs-target="#collapse-two"
                      aria-expanded="true"
                      aria-controls="collapse-two">
                      <span class="accordion-title fs-3">Size</span>
                    </button>
                  </div>
                  <div
                    id="collapse-two"
                    class="accordion-collapse collapse show"
                    aria-labelledby="heading-two">
                    <div class="accordion-body">
                      <a href="{{url_for('market.shopsize', key=1)}}">XS</a>
                      <a href="{{url_for('market.shopsize', key=2)}}">S</a>
                      <a href="{{url_for('market.shopsize', key=3)}}">M</a>
                      <a href="{{url_for('market.shopsize', key=4)}}">L</a>
                    </div>
                  </div>
                </div>

                <a href="#" class="btn-link text-uppercase item-anchor"
                  >Reset All Filters</a
                >
              </div>
            </div>
          </div>
        </aside>
      </div>
    </div>
  </div>

  <div class="col-md-6 text-md-end mt-3 mt-md-0">
    <p>© Copyright 2023. All rights reserved. Design by Cloth Charm</p>
  </div>

  {%endblock%}
</body>

apps/market/templates/market/wishlist.html
{%extends "detector/index.html"%} {%block title%}お気に入りリスト{%endblock%}
{%block content%}
<body class="homepage">
  <main>
    <section>
      <div class="container">
        <div class="d-flex justify-content-between align-items-center mt-5">
          <h4>お気に入りリスト</h4>
          <nav class="breadcrumb fs-6">
            <a class="breadcrumb-item nav-link" href="#">Home</a>
            <a class="breadcrumb-item nav-link" href="#">Pages</a>
            <span class="breadcrumb-item active" aria-current="page"
              >Wishlist</span
            >
          </nav>
        </div>
      </div>
    </section>

    <section id="Wishlist" class="py-5 mb-5">
      <div class="container">
        <div class="row text-dark my-3">
          <div class="col-5 text-uppercase">商品</div>
          <div class="col-2 text-uppercase">価格</div>
          <div class="col-2 text-uppercase">在庫</div>
        </div>
        {% for product in products %}
        <div class="product-wrapper">
          <div class="product-item row align-items-center mb-4">
            <div class="col-4 col-md-1 d-flex align-items-center text-left">
              <a href="{{url_for('market.detail', id=product.id)}}">
                <img
                  srcset="
                    {{url_for('detector.image_file',filename=product.image_path)}}
                  "
                  alt="wishlist"
                  class="img-fluid" />
              </a>
            </div>
            <div class="col-8 col-md-4">
              <h3 class="item-title text-uppercase fs-5">
                <a href="{{url_for('market.detail', id=product.id)}}"
                  >{{product.image_name}}</a
                >
              </h3>
            </div>
            <div class="col-3 col-md-2 product-price text-left">
              <span class="item-price">{{product.price}}円</span>
            </div>
            {% if product.sold == True %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: red">購入不可</span>
            </div>
            {% else %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: blue">購入可</span>
            </div>
            <div class="col-3 col-md-2 wishlist-add text-left">
              <a
                class="btn btn-outline-dark text-uppercase"
                title="Add to Cart"
                href="{{url_for('market.detail', id=product.id)}}"
                >購入する</a
              >
            </div>
            {% endif %} {% if product.rental == True %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: red">レンタル不可</span>
            </div>
            {% else %}
            <div class="col-3 col-md-2 wishlist-stock text-left">
              <span class="item-stock" style="color: blue">レンタル可</span>
            </div>
            <div class="col-3 col-md-2 wishlist-add text-left">
              <a
                class="btn btn-outline-dark text-uppercase"
                title="Add to Cart"
                href="{{url_for('market.rental', id=product.id)}}"
                >レンタルする</a
              >
            </div>
            {% endif %}

            <div class="col-3 col-md-1 text-left">
              <div class="cart-remove">
                <a href="#">
                  <svg width="32px">
                    <use xlink:href="#trash"></use>
                  </svg>
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </section>
  </main>
  {%endblock%}
</body>