apps/detector/views.py
from flask import (
    Blueprint,
    render_template,
    request,
    make_response,
    session,
    flash,
    redirect,
    url_for,
    current_app,
    send_from_directory,
)
from flask_login import current_user, login_required
from apps.detector.models import UserImage, Favorite
from apps.crud.models import User
from apps.app import db
from apps.detector.forms import UploadImageForm, DeleteForm
from apps.crud.forms import UpdateForm
from flask_paginate import Pagination, get_page_args
import uuid
from pathlib import Path

dt = Blueprint("detector", __name__, template_folder="templates")


@dt.route("/", methods=["GET"])
def index():
    images = UserImage.query.order_by(UserImage.id.desc()).all()

    return render_template("detector/index.html", images=images)


@dt.route("/images/<path:filename>")
def image_file(filename):
    return send_from_directory(current_app.config["UPLOAD_FOLDER"], filename)


@dt.route("/upload", methods=["GET", "POST"])
@login_required
def upload_images():
    form = UploadImageForm()

    if form.validate_on_submit():
        file = form.image.data
        ext = Path(file.filename).suffix
        image_uuid_file_name = str(uuid.uuid4()) + ext

        image_path = Path(current_app.config["UPLOAD_FOLDER"], image_uuid_file_name)
        file.save(image_path)

        user_image = UserImage(
            user_id=current_user.id,
            image_path=image_uuid_file_name,
            image_name=form.title.data,
            explain=form.explain.data,
            category=form.category.data,
            size=form.size.data,
            condition=form.condition.data,
            price=form.price.data,
            send=form.send.data,
            sexual=form.sexual.data,
        )

        db.session.add(user_image)
        db.session.commit()

        return redirect(url_for("detector.index"))
    return render_template("detector/toukou.html", form=form)


@dt.route("/mypage")
@login_required
def mypage():
    users = User.query.filter_by(id=current_user.id).first()
    user_images = UserImage.query.filter_by(user_id=current_user.id).all()
    delete_form = DeleteForm()

    return render_template(
        "detector/mypage.html",
        users=users,
        user_images=user_images,
        delete_form=delete_form,
    )


@dt.route("/images/delete/<string:image_id>", methods=["POST"])
@login_required
def delete_image(image_id):
    try:
        db.session.query(UserImage).filter(UserImage.id == image_id).delete()
        db.session.commit()

    except:
        db.session.rollback()

    return redirect(url_for("detector.index"))


@dt.route("/editprofile/<int:id>", methods=["POST", "GET"])
@login_required
def editprofile(id):
    user = User.query.filter_by(id=id).first()
    updateform = UpdateForm()

    if request.method == "POST":
        if updateform.validate_on_submit():
            file = updateform.image.data
            ext = Path(file.filename).suffix
            image_uuid_file_name = str(uuid.uuid4()) + ext

            image_path = Path(current_app.config["UPLOAD_FOLDER"], image_uuid_file_name)
            file.save(image_path)

            user.icon_path = (image_uuid_file_name,)
            user.username = (updateform.username.data,)
            user.profile = (updateform.explain.data,)
            user.address = (updateform.address.data,)
            user.phone = updateform.phone.data

            db.session.commit()
            return redirect(url_for("detector.mypage"))

    return render_template(
        "detector/editprofile.html", user=user, updateform=updateform
    )


@dt.route("/notices")
def notices():
    return render_template("detector/notice.html")

apps/detector/templates/detector/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>TOPページ</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
  </head>

  <body>
    <!-- ナビゲーションバーを作成する -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('detector.index') }}"
          >TOPページ</a
        >
        <!-- 画像検索フォームを追加する -->

        <ul class="navbar-nav">
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <span class="nav-link">{{ current_user.username }}</span>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('auth.logout') }}" class="nav-link"
              >ログアウト</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">ログイン</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- block contentをsection class="container"で囲む -->
    <main>
      <section class="container">{% block content %}{% endblock %}</section>
    </main>
  </body>
</html>

apps/detector/templates/detector/editprofile.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>プロフィール編集</title>
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='css/profile_edit.css')}}" />
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='css/profile_style.css')}}" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500&family=Prata&display=swap"
      rel="stylesheet" />
  </head>
  <body>
    <div class="container">
      <!-- <p>← TOPに戻る</p>   -->
      <form
        action="{{url_for('detector.editprofile', id=user.id)}}"
        method="post"
        enctype="multipart/form-data">
        <div class="left">
          <!-- <input type="file" id="imageUpload" accept="image/*" multiple /> -->
          <label for="imageUpload" id="imageLabel"
            ><u>プロフィール画像を選択</u></label
          >
          {{updateform.csrf_token}} {{updateform.image(id="imageUpload")}}
          <div class="image-preview">
            <!-- ここに選択した画像が表示されます -->
          </div>
        </div>
        <div class="right">
          <h1><b>プロフィール内容入力フォーム</b></h1>
          <!-- <p class="Form-Item-Label">
                    <span class="Form-Item-Label-Required">必須</span>商品タイトル
                  </p> -->
          {{updateform.username.label}} {{updateform.username}}
          {{updateform.explain.label}} {{updateform.explain}}
          {{updateform.address.label}} {{updateform.address}}
          {{updateform.phone.label}} {{updateform.phone}} {{updateform.submit}}
        </div>
      </form>
    </div>

    <script src="{{url_for('static', filename='js/profile_edit.js')}}"></script>
  </body>
</html>

apps/detector/templates/detector/mypage.html
{%extends "detector/index.html"%} {%block title%}マイページ{%endblock%} {%block
content%}
<body>
  <link
    rel="stylesheet"
    href="{{url_for('static', filename='css/mypage.css')}}" />

  <header>
    <div class="container">
      <div class="profile">
        <div class="profile-image">
          <img
            src="{{url_for('detector.image_file',filename=users.icon_path)}}"
            width="152px"
            height="152px"
            alt="アイコン" />
        </div>

        <div class="profile-user-settings">
          <h1 class="profile-user-name">{{users.username}}</h1>

          <button class="btn profile-edit-btn">
            <a href="{{url_for('detector.editprofile', id=users.id)}}"
              >プロフィールを編集</a
            >
          </button>

          <button
            class="btn profile-settings-btn"
            aria-label="profile settings">
            <i class="fas fa-cog" aria-hidden="true"></i>
          </button>
        </div>

        <div class="profile-stats">
          <ul>
            <li><span class="profile-stat-count">30</span> 出品</li>
            <li><span class="profile-stat-count">188</span> フォロワ―</li>
            <li><span class="profile-stat-count">206</span> フォロー中</li>
          </ul>
        </div>

        <div class="profile-bio">
          <h3>Profile</h3>
          <p>{{users.profile}}</p>
        </div>
      </div>
      <!-- End of profile section -->
    </div>
    <!-- End of container -->
  </header>

  <main>
    {%for image in user_images%}
    <div class="card col-md-7 dt-image-content">
      <header class="d-flex justify-content-between">
        <div class="dt-image-username" style="font-size: 20px">
          {{image.image_name}} {% if image.sold == True%}
          <span class="badge bg-danger">売却済み</span>
          {%endif%} {%if image.rental == True%}
          <span class="badge bg-danger">レンタル済み</span>
          {%endif%}
        </div>
        <div class="p-2">
          <form
            action="{{url_for('detector.delete_image', image_id=image.id)}}"
            method="post">
            {{delete_form.csrf_token}} {%if current_user.id == image.user_id %}
            {{delete_form.submit(class="btn btn-danger",
            style="font-size:15px")}} {%else%} {{delete_form.submit(class="btn
            btn-danger", disabled="disabled")}} {%endif%}
          </form>
        </div>
      </header>
      <div class="gallery-item" tabindex="0">
        <img
          src="{{url_for('detector.image_file',filename=image.image_path)}}"
          class="gallery-image"
          alt="" />

        <div class="gallery-item-info">
          <ul>
            <li class="gallery-item-likes">
              <span class="visually-hidden">Likes：</span
              ><i class="fas fa-heart" aria-hidden="true"
                >Name：{{image.image_name}}
              </i>
            </li>
            <li class="gallery-item-comments">
              <span class="visually-hidden">Comments:</span
              ><i class="fas fa-comment" aria-hidden="true"
                >Price：{{image.price}}</i
              >
            </li>
          </ul>
        </div>
      </div>
    </div>

    {%endfor%}

    <!-- End of container -->
  </main>

  <footer id="footer" class="mt-5">
    <div class="col-md-6 text-md-end mt-3 mt-md-0">
      <p>© Copyright 2023. All rights reserved. Design by Cloth Charm</p>
    </div>
    {%endblock%}
  </footer>
</body>

apps/detector/templates/detector/notice.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <title>参考</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="format-detection" content="telephone=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="keywords" content="ecommerce,fashion,store">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="icomoon/icomoon.css">
  <link rel="stylesheet" type="text/css" href="css/vendor.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
  <link rel="stylesheet" type="text/css" href="style.css">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500&family=Prata&display=swap" rel="stylesheet">

  <meta charset="UTF-8">
  <title>通知一覧</title>
      <link rel="stylesheet" href="{{url_for('static', filename='css/notice.css')}}">
      <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
</head>

<body>

    <div class="w">

        <h1>通知一覧</h1>

        <ul class="news-list">
            <li class="item">
                <a href="#">
                    <p class="date">2024/03/04</p>
                    <p class="category"><span>ようこそ</span></p>
                    <p class="title">会員登録ありがとうございます！<br>これからCloth Charmでのお買い物を楽しみましょう。</p>
                </a>
            </li>
            <li class="item">
                <a href="#">
                    <p class="date">2024/03/02</p>
                    <p class="category"><span>お知らせ</span></p>
                    <p class="title">ここにお知らせが入りますここにお知らせが入ります</p>
                </a>
            </li>
            <li class="item">
                <a href="#">
                    <p class="date">2024-03/02</p>
                    <p class="category"><span>お知らせ</span></p>
                    <p class="title">ここにお知らせが入りますここにお知らせが入ります</p>
                </a>
            </li>

            <li class="item">
            <a href="#">
                <p class="date">2023/10/13</p>
                <p class="category"><span>お知らせ</span></p>
                <p class="title">ここにお知らせが入りますここにお知らせが入ります</p>
            </a>
        </li>

        <li class="item">
            <a href="#">
                <p class="date">2023/10/13</p>
                <p class="category"><span>お知らせ</span></p>
                <p class="title">ここにお知らせが入りますここにお知らせが入ります</p>
            </a>
        </li>

        <li class="item">
        <a href="#">
            <p class="date">2023/10/13</p>
            <p class="category"><span>お知らせ</span></p>
            <p class="title">ここにお知らせが入りますここにお知らせが入ります</p>
        </a>
        </li>

        <li class="item">
        <a href="#">
            <p class="date">2023/10/13</p>
            <p class="category"><span>お知らせ</span></p>
            <p class="title">ここにお知らせが入りますここにお知らせが入ります</p>
        </a>
        </li>

        <li class="item">
        <a href="#">
            <p class="date">2023/10/13</p>
            <p class="category"><span>お知らせ</span></p>
            <p class="title">ここにお知らせが入りますここにお知らせが入ります</p>
        </a>
        </li>

        <li class="item">
        <a href="#">
            <p class="date">2023/10/13</p>
            <p class="category"><span>お知らせ</span></p>
            <p class="title">ここにお知らせが入りますここにお知らせが入ります
        </li>
        </ul>

    </div>


</body>

<footer id="footer" class="mt-5">

    <div class="col-md-6 text-md-end mt-3 mt-md-0">
      <p>© Copyright 2023. All rights reserved. Design by Cloth Charm</p>
    </div>
  </div>
</div>
</div>
</footer>
<!-- <script src="js/jquery.min.js"></script>
<script src="js/plugins.js"></script>
<script src="js/SmoothScroll.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script> -->
<script src="{{url_for('static', filename='js/notice.js')}}"></script>
</body>

</html>

</html>

apps/detector/templates/detector/toukou.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>出品内容入力</title>
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='css/toukou.css')}}" />
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='css/style.css')}}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500&family=Prata&display=swap"
      rel="stylesheet" />

    <div class="container">
      <div class="right">
        <h1><b>出品内容入力フォーム</b></h1>
        <form
          action="{{ url_for('detector.upload_images') }}"
          method="post"
          enctype="multipart/form-data"
          novalidate="novalidate">
          {{ form.csrf_token }}
          <div>
            <label>
              <span
                >{{ form.title(size=30, class="form-control",
                placeholder="商品名") }}</span
              > </label
            ><br />

            <label>
              <span
                >{{ form.sexual(class="form-control", placeholder="性別")
                }}</span
              > </label
            ><br />

            <label>
              <span
                >{{ form.explain(class="form-control", placeholder="説明")
                }}</span
              > </label
            ><br />

            <label>
              <span
                >{{ form.category(class="form-control",
                placeholder="カテゴリー") }}</span
              > </label
            ><br />

            <label>
              <span
                >{{ form.size(class="form-control", placeholder="サイズ")
                }}</span
              > </label
            ><br />

            <label>
              <span
                >{{ form.condition(class="form-control", placeholder="状態")
                }}</span
              > </label
            ><br />

            <label>
              <span
                >{{ form.price(class="form-control", placeholder="値段")
                }}</span
              > </label
            ><br />

            <label>
              <span
                >{{ form.send(class="form-control", placeholder="発送") }}</span
              > </label
            ><br />

            <label>
              <span> {{ form.image(class="form-control-file") }} </span>
            </label>
          </div>
          {% for error in form.image.errors %}
          <span style="color: red">{{ error }}</span>
          {% endfor %}
          <hr />
          <div>
            <label> {{ form.submit(class="btn btn-primary") }} </label>
          </div>
        </form>
      </div>
    </div>
    <script src="{{url_for('static', filename='js/toukou.js')}}"></script>
  </head>
</html>

apps/detector/templates/detector/upload.html
{% extends "detector/index.html" %}
{% block content %}
<div>
    <h4>出品</h4>
    <p>商品情報を入力してください。</p>
    <form action="{{ url_for('detector.upload_images') }}" method="post" enctype="multipart/form-data"
        novalidate="novalidate">
        {{ form.csrf_token }}
        <div>
            <label>
                <span>{{ form.title(size=30, class="form-control", placeholder="商品名") }}</span>
            </label><br>

            <label>
                <span>{{ form.explain(class="form-control", placeholder="説明") }}</span>
            </label><br>

            <label>
                <span>{{ form.category(class="form-control", placeholder="カテゴリー") }}</span>
            </label><br>

            <label>
                <span>{{ form.size(class="form-control", placeholder="サイズ") }}</span>
            </label><br>

            <label>
                <span>{{ form.condition(class="form-control", placeholder="状態") }}</span>
            </label><br>

            <label>
                <span>{{ form.price(class="form-control", placeholder="値段") }}</span>
            </label><br>

            <label>
                <span> {{ form.image(class="form-control-file") }} </span>
            </label>
        </div>
        {% for error in form.image.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <hr />
        <div>
            <label> {{ form.submit(class="btn btn-primary") }} </label>
        </div>
    </form>
</div>
{% endblock %}